language: java
sudo: true
jdk: oraclejdk8

addons:
  chrome: 'stable'

# services:
#   - docker

env:
  matrix:
    - TEST_SUITE=integration NODE_VERSION=8
  global:
    - COUCH_URL=http://admin:pass@localhost:5984/medic-test
    - COUCH_NODE_NAME=nonode@nohost
    - PUBLIC_UPLOAD_URL=http://admin:pass@localhost:5984
    # - [-z "$UPLOAD_URL"] && EXTERNAL_CONTRIBUTOR=true || EXTERNAL_CONTRIBUTOR=false
    - EXTERNAL_CONTRIBUTOR=false

before_script:
  # - mkdir tests/logs
  # - nvm use $NODE_VERSION
  # - ./scripts/travis/npm-init
  # - npm install -g grunt-cli
  # - npm install -g horticulturalist
  # - ./scripts/travis/couch-config
  - if [[ -z "$UPLOAD_URL" ]]; then export EXTERNAL_CONTRIBUTOR=true fi
  - echo ">>>>>>>>>>>>>>>>>>>EXTERNAL_CONTRIBUTOR=${EXTERNAL_CONTRIBUTOR}"
